### ISSUE TITLE
DuplicateWidgetIDError

### ISSUE THREAD

**Issue by om-pramod** [andfanilo/social-media-tutorials#1]
![Screenshot (66)](https://user-images.githubusercontent.com/86967995/207772791-2c4288ab-3271-43dd-bee8-ca8aa36dd8f5.png)

After few conversation with bot, it generates this error

**Comment by ammaarkhan** [comment]
This might help you: https://discuss.streamlit.io/t/duplicate-widgetid-error/4739. I faced the same issue. I just changed 'input_text' to 'text' on lines 25 and 36. Referring to this file: https://github.com/andfanilo/social-media-tutorials/blob/master/20220124-streamlitchat/streamlit_app.py

Hope this helps!

**Comment by andfanilo** [comment]
Should be solved by #2
